### ISSUE TITLE
unfollow comments

### ISSUE THREAD

**Issue by HolySoap** [niklas-englert/9GAG-Controls#1]
Is it possible to add an option to automatically unfollow a comment when you reply to a comment?

**Comment by niklas-englert** [comment]
Thanks for the feature request!

No, currently it is not possible to automatically unfollow a comment and I sadly I can't make the effort to change that at the time.  
9GAGs JavaScript code is compressed and therefore unreadable for humans, which would make it very difficult for me to figure out how to implement automatic unfollowing. Design changes, changes on standardized ads (e.g. Google AdSense) and videos are in comparison "very easy" to do.

Sorry, I will close this issue and hope you have still a lot of fun with the extension.
