### ISSUE TITLE
Feature request: Only allow video to play at a time and when roughly centered

### ISSUE THREAD

**Issue by kelderek** [niklas-englert/9GAG-Controls#2]
I would appreciate it if the plugin only allowed video to start auto-playing when they are roughly centered - this could use the same logic that the zoom button uses to select the correct item to zoom.  I have a tall screen so I often miss the beginning of videos when I am reading the previous post because it came on screen enough to start auto-playing.

Likewise when I scroll and a new post gets roughly centered, the old one should automatically stop playing.  It is annoying having multiple videos playing at that same time.

Thank you!

**Comment by niklas-englert** [comment]
Thanks for the feature request!

I'll look in to it if I solved [my current problem](https://discourse.mozilla.org/t/my-newest-addon-version-is-disabled-by-mozilla-but-has-no-validation-issues/62570) with the verification of my releases on Mozilla ADD-ONS. In fact I have experienced this problem by myself already. I don't want to promise anything, but maybe it will be implemented by the end of next month (July).  
I'll inform you here in this issue about updates on this topic.

Anyway, in my own interest: Do you use the extension for Chrome or Firefox and how did you discover it?

**Comment by kelderek** [comment]
Thanks for the quick reply!  I use Firefox and was wondering why it still showed 1.1.1 in Firefox Add-ons even though the Chrome store and GitHub show 1.2.0.

I haven't done any real coding in a very long time, but if you need someone to help beta test just let me know.

Danke sehr!

**Comment by kelderek** [comment]
I forgot to answer how I discovered your add-on.  I was frustrated with the auto playing videos, hidden video controls, and mute button on top of the pause button.  I searched firefox add-ons for "9gag" and yours looked closest to what I wanted.

**Comment by niklas-englert** [comment]
So...  your feature is implemented in [version 1.3.0](https://github.com/niklas-englert/9GAG-Controls/releases) (commit 0ddf87e) and with that, this issue was closed.

The new version is submitted to the individual stores, but it will take a while until it's reviewed. If that is finished, it would be really kind if you could give me a short feedback then, so I know that everything works as expected.

**Comment by kelderek** [comment]
Excellent, thank you!

**Comment by kelderek** [comment]
It looks like the Firefox add-on store already approved the new version, I just did a check for updates and it came right in.  I tried it out and didn't think it was working at first, because I didn't realize I had to check the Center Play box (I didn't see it).  Once I checked the box it worked perfectly!  That solves a major annoyance for me :)
