### ISSUE TITLE
An option to hide controls

### ISSUE THREAD

**Issue by ArkadiuszNiemiec** [niklas-englert/9GAG-Controls#3]
Could we please get an option to hide control panel on videos/gifs? 
Great work with the addon, love it!

**Comment by niklas-englert** [comment]
I'm not sure if I fully understand your request.  
Video controls is a native feature of your web browser, which is "just" activated for all videos by my extension (see [W3C standards](https://www.w3.org/TR/2011/WD-html5-20110113/video.html#attr-media-controls)).  
The control panel should only be displayed (/faded in) if the cursor has hovered over the video element. So it should be invisible if you aren't  interacting with the video anyway.
- If the controls are constantly visible (without you having previously hovered over the video), then that's an issue with your local browser. Please make sure your browser is up-to-date.
- But in case you bothered by seeing the controls although you having previously hovered over the video, then I don't understand why you want this specific feature to be hidden via options? I mean... that's the whole point of the extension.

**Comment by ArkadiuszNiemiec** [comment]
I see, this must be an issue with my FF then. Controls are visible by default and disappear only if I click the video and the move the cursor away. By default, when scrolling, I have controls on every video and gif.
What you described is what I wanted, so there should be no issue 😄 Thank you again!
