### ISSUE TITLE
Extension bug on opening multiple gag tab

### ISSUE THREAD

**Issue by Paramirage** [niklas-englert/9GAG-Controls#4]
Sometimes when i want to open multiple gag in multiple tab for some tab extension does not load. It also removes 9gag section like funny or politics from favorite from left side bar(after browser restart). To solve this we have to reload every single tab for this which is troublesome. you can test it opening at least 10-15 tabs in Firefox. please fix this.

Also it removes tick from center play and black automatically for this problem.

**Comment by niklas-englert** [comment]
I couldn't reproduce the problem you have described. I tried up to 40 open tabs being logged in and not logged in. The same post in every tab vs. all different videos. I tested on Firefox and Chrome. etc.

It sounds more like a problem with your local machine and 9gag itself not loading correctly if so many tabs are open.  
The only explanation I can come up with, is the following: Your browser hits a maximum concurrent HTTP request or RAM limit with so many tabs open which causes continuous and self-renewing [blocking](https://blog.bluetriangle.com/blocking-web-performance-villain). But this browser extension can only be run if the page has fully finished loading (See `"run_at": "document_end"` in [src/manifest.json](https://github.com/niklas-englert/9GAG-Controls/blob/master/src/manifest.json#L26)).

However, I tried improving the performance of the extension by making the synchronization of settings between tabs more efficient and less resource intensive. The **[new release v1.3.5](https://github.com/niklas-englert/9GAG-Controls/releases/tag/v1.3.5)** rolls out soon. Maybe this makes your problem better somehow.

**Comment by Paramirage** [comment]
I have cleared all cache and cookies of 9gag. 600 tab is present in my firefox and there is roughly 20 of them are from 9gag. Also tab does not load untill i click them. This happen when i tried to open multiple tab. This is happening on the 5th of 9gag tab. rest of tab are suspended. So i am not seeing any issue. 

To clear conception i tried it with new profile and it happened to me again.

**Comment by Paramirage** [comment]
maybe found the culprit. I am not sure though. Have to check for some days after your update. It is adblock called ublock origin. 

nope it still exists even with new profile. Also new version is making uncheck central play and dark mode at the first load of browser which did not happen before. Turning to old version to check further with disabled adblock.

**Comment by Paramirage** [comment]
nope it still exists even with new profile.

**Comment by Paramirage** [comment]
Also new version is making uncheck central play and dark mode at the first load of browser which did not happen before.

**Comment by Paramirage** [comment]
New version is not working and my machine has 32gb ram which i think enough for this . I am also not finding any cause for this but it is happening.
