### ISSUE TITLE
9gag pure black gone 

### ISSUE THREAD

**Issue by Paramirage** [niklas-englert/9GAG-Controls#5]
From today 9gag changed something regarding their ui design which makes black option of this addon worthless. We are not getting pure black anymore. Please fix it in next update.

**Comment by niklas-englert** [comment]
Thanks for reporting!

Version [1.4.0](https://github.com/niklas-englert/9GAG-Controls/releases/tag/v1.4.0) was released and the build is currently in review at Chrome Web Store and Mozilla AddOns.  
This may take a couple of hours to finish and some more time for your browser to auto-update. The latter can be accelerated manually by going on `chrome://extensions/` or `about:addons` and check for updates manually.
