### ISSUE TITLE
Feature request - post detail URL 

### ISSUE THREAD

**Issue by veleminsky** [niklas-englert/9GAG-Controls#6]
I would really appreciate, if the plugin could change the URL of the post's detail so that when I click on it, it will automatically open `Comment section` instead of `Related section`.

That means only to add hash to the post URL `#comment`.

Thanks!

**Comment by niklas-englert** [comment]
Yeah, I'm annoyed by that too. I was sure that this feature wouldn't last a week... but here we are. It is a shame that sites like this don't understand the demands of their own users.
I added an option "default comments". I'll roll back this change when 9GAG has returned to their senses.

Version [1.4.2](https://github.com/niklas-englert/9GAG-Controls/releases/tag/v1.4.2) is released and the build is currently in review at Chrome Web Store and Mozilla AddOns.  
This may take a couple of hours to finish and some more time for your browser to auto-update. The latter can be accelerated manually by going on `chrome://extensions/` or `about:addons` and checking for updates manually.

**Comment by veleminsky** [comment]
Awesome, thanks for such a quick response!
