### ISSUE TITLE
Feature request: auto unmute

### ISSUE THREAD

**Issue by chaoscreater** [niklas-englert/9GAG-Controls#7]
Hi,

I'd like to make a request for auto-unmute on the videos please. They are muted by default and I have to click on the unmute button on every video before playing, which is kinda annoying.

**Comment by chaoscreater** [comment]
Actually never mind, I found my solution here. It doesn't autoplay the videos (which is good) and when you do play, it plays with mute off by default, which is what I want.

https://greasyfork.org/en/scripts/421629-9gag-video-enhancer

**Comment by niklas-englert** [comment]
I accept your request anyway. Others could also benefit from it. Having to press play/unmute for every video is the old mechanic of forums like Reddit. More and more users are getting used to auto play with sound thanks to TikTok and YouTube Shorts... and the last patch was also year ago and over time it ruins the ranking.

Version [1.4.3](https://github.com/niklas-englert/9GAG-Controls/releases/tag/v1.4.3) is released and the build is currently in review at Chrome Web Store and Mozilla AddOns.
This may take a couple of hours to finish and some more time for your browser to auto-update. The latter can be accelerated manually by going on chrome://extensions/ or about:addons and checking for updates manually.
