### ISSUE TITLE
Video Controls Issues

### ISSUE THREAD

**Issue by Aleejonn** [niklas-englert/9GAG-Controls#9]
Hey! great addon,
Only have 1 issue, video controls stay there forever and is kinda annoying, is there any way to disable that?

**Comment by niklas-englert** [comment]
These video controls are a native feature of your web browser, which is "just" activated for all videos by my extension (see [W3C standards](https://www.w3.org/TR/2011/WD-html5-20110113/video.html#attr-media-controls)).

Usually Firefox and Chrome hide the control bar if not hovered over recently (at least on the current desktop Windows and Linux OS versions I test with).

If the controls are constantly visible (without you having previously hovered over the video), then that's an issue with your local browser.

> :information_source: **This is a duplicate of issue #3.**

**Comment by Aleejonn** [comment]
I think it's an issue with firefox, the controls are always visible, that's why me and the other guy want an option to disable them
